// <auto-generated />
using Backend.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.API.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20230413112418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Backend.Model.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConvertedManaCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            ConvertedManaCost = 0.0m,
                            ManaCost = "{0}",
                            Name = "Black Lotus",
                            OracleText = "{T}, Sacrifice Black Lotus: Add three mana of any one color.",
                            SetId = 1
                        },
                        new
                        {
                            CardId = 2,
                            ConvertedManaCost = 2.0m,
                            ManaCost = "{1}{W}",
                            Name = "Balance",
                            OracleText = "Each player chooses a number of lands they control equal to the number of lands controlled by the player who controls the fewest, then sacrifices the rest. Players discard cards and sacrifice creatures the same way.",
                            SetId = 1
                        },
                        new
                        {
                            CardId = 3,
                            ConvertedManaCost = 0.0m,
                            ManaCost = "",
                            Name = "Gaea's Cradle",
                            OracleText = "{T}: Add {G} for each creature you control.",
                            SetId = 2
                        },
                        new
                        {
                            CardId = 4,
                            ConvertedManaCost = 3.0m,
                            ManaCost = "{2}{B}",
                            Name = "Yawgmoth's Will",
                            OracleText = "Until end of turn, you may play lands and cast spells from your graveyard. If a card would be put into your graveyard from anywhere this turn, exile that card instead. ",
                            SetId = 2
                        });
                });

            modelBuilder.Entity("Backend.Model.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("CardCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SetId");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            SetId = 1,
                            Block = "",
                            BlockCode = "",
                            CardCount = 295,
                            Code = "LEA",
                            Name = "Limited Edition Alpha"
                        },
                        new
                        {
                            SetId = 2,
                            Block = "Urza",
                            BlockCode = "usg",
                            CardCount = 365,
                            Code = "USG",
                            Name = "Urza's Saga"
                        },
                        new
                        {
                            SetId = 3,
                            Block = "Masques",
                            BlockCode = "mmq",
                            CardCount = 350,
                            Code = "MMQ",
                            Name = "Mercadian Masques"
                        },
                        new
                        {
                            SetId = 4,
                            Block = "Masques",
                            BlockCode = "mmq",
                            CardCount = 144,
                            Code = "PCY",
                            Name = "Mercadian Masques"
                        });
                });

            modelBuilder.Entity("Backend.Model.Card", b =>
                {
                    b.HasOne("Backend.Model.Set", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Backend.Model.Set", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
